import React from 'react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Download, FileText } from 'lucide-react';

export const MediaKit = ({ creatorData, analyticsData, dealsData }) => {
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(124, 92, 252); // var(--accent-primary)
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('CREATOR MEDIA KIT', 15, 25);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(new Date().toLocaleDateString(), pageWidth - 40, 25);

    // Profile Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.text('Overview', 15, 55);

    doc.setFontSize(11);
    doc.text(`Niche: ${creatorData?.niche || 'Content Creation'}`, 15, 65);
    doc.text(`Topic: ${creatorData?.topic || 'N/A'}`, 15, 72);

    // Stats Table
    doc.setFontSize(16);
    doc.text('Key Performance Metrics', 15, 90);

    const statsData = [
      ['Metric', 'Value'],
      ['Total Views', analyticsData?.kpi?.totalViews?.value?.toLocaleString() || '0'],
      ['Subscribers', analyticsData?.kpi?.totalViews?.value?.toLocaleString() || '0'],
      ['Engagement Rate', `${analyticsData?.kpi?.engagementRate?.value || '0'}%`],
      ['Est. Monthly Revenue', `$${analyticsData?.kpi?.totalRevenue?.value?.toLocaleString() || '0'}`]
    ];

    doc.autoTable({
      startY: 95,
      head: [['Metric', 'Value']],
      body: statsData.slice(1),
      theme: 'striped',
      headStyles: { fillColor: [124, 92, 252] }
    });

    // Content Performance
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(16);
    doc.text('Recent Content Performance', 15, finalY);

    const contentData = (analyticsData?.contentPerformance || []).map(item => [
      item.title,
      item.platform,
      item.views.toLocaleString(),
      `$${item.revenue}`
    ]);

    doc.autoTable({
      startY: finalY + 5,
      head: [['Title', 'Platform', 'Views', 'Revenue']],
      body: contentData,
      theme: 'grid',
      headStyles: { fillColor: [0, 212, 255] }
    });

    // Contact
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Creator Intelligence OS', pageWidth / 2, 285, { align: 'center' });

    doc.save('Creator_Media_Kit.pdf');
  };

  return (
    <button
      onClick={generatePDF}
      className="shiny-button"
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '10px 20px',
        fontSize: '0.9rem'
      }}
    >
      <Download size={18} />
      Generate Media Kit
    </button>
  );
};

export default MediaKit;
